#
# site information
#
title: Guilherme L. Mello
subtitle: Personal Portfolio Website
description: >-
  Guilherme L. Mello personal Portfolio Website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#
# author information
#
author: Gulherme L. Mello
author_img: profile.png
author_email: "guilhermelmello@yahoo.com.br"
author_location: São Paulo - Brasil
#disqus_shortname: #for comments using disqus
author_bio: >-
  Hello, my name is Guilherme Mello. I am a Data Scientist... (TODO)
